### ISSUE TITLE
Fatal Error after activation

### ISSUE THREAD

**Issue by smam2021** [rjcalifornia/job-board-manager#1]
Hello,
I have a Fatal Error after activation:
Call to undefined function elgg_register_library()

Log at time 2021-10-03T14:31:42+00:00 may have more data.

#0 [internal function]: job_board_manager_init('init', 'system', NULL)
#1 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/HandlersService.php(85): call_user_func_array('job_board_manag...', Array)
#2 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php(89): Elgg\HandlersService->call('job_board_manag...', 'event', Array)
#3 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php(173): Elgg\EventsService->trigger('init', 'system', NULL, Array)
#4 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(160): Elgg\EventsService->triggerSequence('init', 'system')
#5 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(49): Elgg\Application\BootHandler->bootApplication()
#6 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(215): Elgg\Application\BootHandler->__invoke()
#7 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(474): Elgg\Application->bootCore()
#8 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(360): Elgg\Application->run()
#9 /home/thesocialonline/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(416): Elgg\Application::route(Object(Elgg\Http\Request))
#10 /home/thesocialonline/public_html/index.php(8): Elgg\Application::index()
#11 {main}

**Comment by rjcalifornia** [comment]
This version is compatible only with elgg 2.3

**Comment by rjcalifornia** [comment]
New version, for elgg 6.x

https://elgg.org/plugins/3046748
